[WIP] Helper methods to make full service usage easier
mobilecoinofficial/forest pull request #102
Opened 2022-01-27 08:49 UTC by iamalwaysuncomfortable

* Full service convenience methods
* Txo Pre-allocation logic to prevent errors in transaction sending

This pull request is WIP

2022-01-31 23:22 UTC, itdaniher requested changes
looks pretty good overall, left some qs&cs!

2022-01-31 23:22 UTC, itdaniher commented on fs_tester.py
> +import logging
should this file go somewhere else?

2022-01-31 23:22 UTC, itdaniher commented on forest/payments_monitor.py
> +FEE = 4000000000
FEE_PMOB?

2022-01-31 23:22 UTC, itdaniher commented on forest/payments_monitor.py
> +    async def get_signal_address(self, address: str = "") -> Optional[str]:
based, I have half-assed this every time I've need it. Glad to put that behind me.

2022-01-31 23:22 UTC, itdaniher commented on forest/payments_monitor.py
> +    async def get_all_txos_for_account(self, account_id: str = "") -> dict:
do we want to just return the unspent TXOs? if so, should this be get_all_utxos?

2022-01-31 23:22 UTC, itdaniher commented on forest/payments_monitor.py
> +    async def cleanup_utxos(
hmmm, a single txo of specified size? not sure that's the right description

2022-01-31 23:35 UTC, iamalwaysuncomfortable commented on forest/payments_monitor.py
> +    async def cleanup_utxos(
This could be changed to a list of txos to cleanup to as well

2022-02-03 23:46 UTC, technillogue commented on forest/payments_monitor.py
> +            params["comment"] = comment
is this right?

2022-02-15 22:18 UTC, iamalwaysuncomfortable reviewed
Changes done

2022-02-23 22:30 UTC, technillogue approved these changes
I haven't fully checked that this won't break anything currently used, but I think this looks good

2022-03-01 02:29 UTC, technillogue commented on forest/payments_monitor.py
> +        specify a list of [mobilecoin address, amount] pairs.
should this be two methods?

2022-07-01 23:55 UTC, closed without merging