send admin a csv of donations every night
mobilecoinofficial/forest pull request #173
Opened 2022-03-22 20:47 UTC by technillogue

2022-03-23 20:19 UTC, transfaeries requested changes
I was able to test that it works by changing the seconds to midnight to be 60 seconds and it gave me my three reports in 3 minutes. Won't be able to know for sure without running overnight so we should do that somehow.

I also obviously, don't have any data so my csv only had headings, so please test with data also.

2022-03-23 20:19 UTC, transfaeries commented on hotline/hotline.py
> +        logging.info("sleeping %s seconds until midnight report")
you're not actually passing the seconds_until_midnight into logging should probably be:

logging.info("sleeping %s seconds until midnight report", seconds_until_midnight.total_seconds())

2022-03-23 20:19 UTC, transfaeries commented on hotline/hotline.py
> +
```suggestion
    @requires_admin
    async def do_report(self) -> None:
        """Generate donation report now as opposed to waiting till midnight"""
        await self.report()
```

2022-03-23 20:19 UTC, transfaeries commented on hotline/hotline.py
> +
might be neat to have a way to request one on the fly as opposed to just waiting till midnight

2022-03-24 03:06 UTC, itdaniher commented
Probably only needs to be weekly? And maybe needs to be duplicated into Charity? We should also discuss deprecating this pipeline at some point...

2022-05-04 05:44 UTC, technillogue commented
idk if there's another better way to do this now but i need it

2023-04-11 15:52 UTC, closed without merging