send payments, reactions, typing, stickers with new auxin content merging
mobilecoinofficial/forest pull request #189
Opened 2022-04-02 00:10 UTC by technillogue

- add send_typing method
- update evilbot
- unused import
- raise NotImplementedError
- add auxin typing messages
- fix group
- restore apparently dropped message.typing and add some logging
- fix AuxinMessage.typing and drop debugs
- add sticker
- fix u8
- new auxin
- also switch over sticker and payment to new content
- add auxin reactions

2022-04-19 23:14 UTC, transfaeries requested changes
Ok, so just fix these bugs and it should be good

2022-04-19 23:14 UTC, transfaeries commented on forest/core.py
>                  await self.send_message(None, "", group=group, content=content)
Needs to send it in the group instead of to the user in DM

2022-04-19 23:14 UTC, transfaeries commented on forest/core.py
>                  None, msg, group=target_msg.group, **other_params
```suggestion
                None, msg, group=target_msg.group_id, **other_params
```

2022-04-19 23:14 UTC, transfaeries commented on forest/core.py
>              group = msg.group or ""
```suggestion
            group = msg.group_id or ""
```

2022-04-19 23:14 UTC, transfaeries commented on forest/core.py
> +                await self.send_message(None, "", group=msg.group, content=content)
```suggestion
                await self.send_message(None, "", group=msg.group_id, content=content)
```

2022-04-19 23:14 UTC, transfaeries commented on sample_bots/tiamat.py
>                  group=response.group,
```suggestion
                group=response.group_id,
```

2022-04-19 23:14 UTC, transfaeries commented on sample_bots/tiamat.py
>                      group=step.message.group,
```suggestion
                    group=step.message.group_id,
```

2022-04-21 02:23 UTC, technillogue commented on forest/core.py
>                  await self.send_message(None, "", group=group, content=content)
wait what was the issue here?

2022-04-29 22:00 UTC, merged