[WIP] clangat
mobilecoinofficial/forest pull request #70
Opened 2022-01-06 06:04 UTC by itdaniher

(this space intentionally left illegible)

2022-01-15 06:16 UTC, technillogue commented on forest/payments_monitor.py
> +            sorted_ = dict(sorted(utxos.items(), key=lambda txo: utxos.get(txo[0], 0)))
wait, you're sorting a dict?

2022-01-15 06:26 UTC, technillogue commented on party/pdict.py
> +class PersistDict(dict):
Do you want to keep both of these?

2022-01-15 06:27 UTC, technillogue commented on party/pdictng.py
> +        base_url: str = "https://vwaurvyhomqleagryqcc.supabase.co/rest/v1/keyvalue",
What's the argument for not using asyncpg for this? Less deps?

2022-01-15 06:31 UTC, technillogue commented on party/pdictng.py
> +        self.thread_pool = concurrent.futures.ThreadPoolExecutor()
I feel like you need to make sure this gets cleaned up on exit?

2022-01-15 06:31 UTC, technillogue commented on party/pdict.py
> +class PersistDict(dict):
Also, do you want pdict in core?

2022-01-15 06:33 UTC, technillogue commented on party/clangat.py
> +        return codecs.encode(msg.text, "rot13")
cute

2022-01-15 06:34 UTC, technillogue commented on party/clangat.py
> +        self.successful_pays: dict[str, list[str]] = PersistDict("list_payouts")
any chance of organizing these somehow?
also, do all of them (e.g. easter eggs) need to have the 90ms writes? or does that actually not matter?

2022-01-15 06:37 UTC, technillogue commented on party/clangat.py
> +        return await self.pending_confirmations[recipient]
oh cool, this is nicer than https://github.com/technillogue/whispr/blob/breeze/breeze_whispr.py#L311

2022-01-15 06:38 UTC, technillogue commented on party/clangat.py
> +        return f"https://signal.me/#p/{self.bot_number}"
swoon

2022-01-15 06:42 UTC, technillogue commented on party/clangat.py
> +        return None
want this in main asap so i can merge into imogen

2022-01-15 06:42 UTC, technillogue commented on party/clangat.py
> +                .lstrip(" ")
aggressive

2022-01-15 06:46 UTC, technillogue commented on contact/contactbot.py
>              await self.mobster.get_address()
Still confused about this, what's the recommended fs setup when creating a new bot?

2022-01-15 06:47 UTC, technillogue commented on forest/core.py
> +                if len(attachment_paths) > 0:
why?

2022-01-15 06:48 UTC, technillogue commented on forest/message.py
> -            return
I think this is still necessary in some edge case?

2022-01-15 06:48 UTC, technillogue commented on forest/payments_monitor.py
> +                pass
We don't actually use this anywhere

2022-01-15 06:50 UTC, technillogue commented on party/cleanup.py
> +def get_phone_numbers_from_csv(csv_name=glob.glob("*.csv")[0]):
classic

2022-01-15 20:34 UTC, technillogue commented on party/clangat.py
> +        self.pending_orders: dict[str, str] = PersistDict("pending_orders")
duplicated

2022-01-21 04:49 UTC, itdaniher commented on forest/payments_monitor.py
> +            sorted_ = dict(sorted(utxos.items(), key=lambda txo: utxos.get(txo[0], 0)))
dicts are sorted now! this builds a dict containing the utxo id mapped to the value in order!

2022-01-21 04:50 UTC, itdaniher commented on party/pdict.py
> +class PersistDict(dict):
I'm having second thoughts about merging this branch. I might make a new branch, port clangat to pdictng, and merge that instead?

2022-01-21 04:51 UTC, itdaniher commented on party/pdictng.py
> +        base_url: str = "https://vwaurvyhomqleagryqcc.supabase.co/rest/v1/keyvalue",
a) fewer deps b) building a drop-in replacement "later" that will be backed by durable objects; http semantics vibe with me here.

2022-01-21 04:53 UTC, itdaniher commented on party/clangat.py
> +        return await self.pending_confirmations[recipient]
yeah! I'm quite happy with how this worked out.

2022-01-21 04:54 UTC, itdaniher commented on party/clangat.py
> +        self.successful_pays: dict[str, list[str]] = PersistDict("list_payouts")
they're all captured in self.state for easy dump / inspection

easter eggs could be asynchronously backed up, but this offers good behavior in my opinion.

2022-01-21 04:55 UTC, itdaniher commented on party/clangat.py
> +        self.successful_pays: dict[str, list[str]] = PersistDict("list_payouts")
I started with a smaller fraction of these, added them as I needed them. The ability to "add columns" to your table with no migration is one of the overpowered parts of pdict.

2022-01-21 04:55 UTC, itdaniher commented on party/clangat.py
> +        return None
sorry it took me a week! but it's now in main!

2022-01-21 04:55 UTC, itdaniher commented on party/clangat.py
> +                .lstrip(" ")
fixed in main!

2022-01-21 04:56 UTC, itdaniher commented on forest/payments_monitor.py
> +                pass
aha, well we'll remove it separately.

2022-01-21 04:57 UTC, itdaniher commented on party/cleanup.py
> +def get_phone_numbers_from_csv(csv_name=glob.glob("*.csv")[0]):
going to put this behind file download, to add lists from csv file "soon"

2022-01-21 04:57 UTC, itdaniher commented on forest/message.py
> -            return
haven't encountered a situation where it's needed!

2022-01-21 04:58 UTC, itdaniher commented on party/pdictng.py
> +        self.thread_pool = concurrent.futures.ThreadPoolExecutor()
haven't seemed to? unsure. I'll investigate.

2022-01-21 04:58 UTC, itdaniher commented on party/clangat.py
> +        return codecs.encode(msg.text, "rot13")
thanks :pray:

2022-01-21 04:59 UTC, itdaniher commented on party/clangat.py
> +        return f"https://signal.me/#p/{self.bot_number}"
<3

2022-01-21 05:00 UTC, itdaniher commented on contact/contactbot.py
>              await self.mobster.get_address()
been doing it with fsr? unsure if that's best.

2022-01-21 05:00 UTC, itdaniher commented on forest/core.py
> +                if len(attachment_paths) > 0:
I forget.

2022-01-21 22:08 UTC, technillogue commented on party/pdict.py
> +class PersistDict(dict):
pdictng in core kinda makes sense

2022-01-21 22:11 UTC, technillogue commented on forest/message.py
> -            return
the elif line 53 will error if not self.text but this irrelevant with recent changes in main

2022-01-21 22:14 UTC, technillogue commented on party/pdictng.py
> +        base_url: str = "https://vwaurvyhomqleagryqcc.supabase.co/rest/v1/keyvalue",
fair enough. i'm pretty sure there's a latency hit for using http instead of the pg binary protocol asyncpg uses, and another for going through haskell, but it prolly doesn't matter

2022-01-21 22:14 UTC, technillogue commented on party/pdictng.py
> +        self.thread_pool = concurrent.futures.ThreadPoolExecutor()
you're removing this in favor of locks anyway, right?

2022-01-21 22:16 UTC, technillogue commented on contact/contactbot.py
>              await self.mobster.get_address()
either revert this or delete the entire block with a note in the readme about fsr using for this

2022-01-21 22:17 UTC, technillogue commented on forest/core.py
> +                if len(attachment_paths) > 0:
revert this, the only difference is if glob returned None then you get an error, but glob always returns a list. otherwise equivalent

2022-01-21 22:19 UTC, technillogue commented on forest/payments_monitor.py
> +    async def get_all_txos_for_account(self):
?

2022-01-21 22:21 UTC, technillogue commented on party/clangat.py
>          self.event_limits: dict[str, int] = PersistDict("event_limits")
pending_orders above is still duplicated

2022-01-21 22:30 UTC, technillogue requested changes

2022-01-21 22:30 UTC, technillogue commented on party/pdictng.py
> +                    ),
Pick a variant of ON CONFLICT DO UPDATE: https://postgrest.org/en/stable/api.html#upsert. Maybe  https://postgrest.org/en/stable/api.html#put  but I'm not entirely sure of the differences here. It should definitely be a single query though

2022-01-21 22:30 UTC, technillogue commented on party/pdictng.py
> +            self.dict_.update(**kwargs)
maybe move this to be right after the __init__ for readability

2022-01-21 22:30 UTC, technillogue commented on party/pdictng.py
> +        "keyvalue_key__key" UNIQUE CONSTRAINT, btree (key_)
adore putting this here

2022-01-21 22:30 UTC, technillogue commented on forest/payments_monitor.py
> +    def __init__(self):
?

2022-01-21 22:30 UTC, technillogue commented on forest/core.py
> +    return web.json_response((await session.wait_resp(future_key=future_key)).blob)
merge with recent main change

2022-01-21 22:33 UTC, itdaniher commented on party/pdictng.py
> +        self.thread_pool = concurrent.futures.ThreadPoolExecutor()
oh yeah, already did

2022-01-21 23:03 UTC, technillogue commented on party/pdictng.py
> +     key_       | text             |           | not null |
replace key with id and key_ with key, and i think add a unique constraint on just key without the identity

2022-01-22 07:02 UTC, closed without merging