Created Readme for imogen, using a theoretical manpage.
mobilecoinofficial/forest pull request #79
Opened 2022-01-11 20:28 UTC by transfaeries

Closes #78 
Will explain how imogen works for users, with examples and the like.

2022-01-19 22:26 UTC, technillogue requested changes

2022-01-19 22:26 UTC, technillogue commented on imogen/README.md
Let's just remove this for now, since it's not enabled rn

2022-01-19 22:26 UTC, technillogue commented on imogen/README.md
> +Experimental feature
idem

2022-01-19 22:26 UTC, technillogue commented on imogen/README.md
>  Mark Next Transaction as Tip. Only usable in DMs. /canceltip cancels registering the next payment as a tip.
this needs to be updated with the new spec

2022-01-21 00:45 UTC, technillogue commented on imogen/README.md
> +)
hmmmmmmmmmmm

i guess let's only keep i, imogen - i want people to only be in one group and not to dm imogen by default, i think

2022-01-24 21:18 UTC, transfaeries commented on imogen/README.md
> +)
I removed Imogen Public, and I moved the DM link to the Payments section. Since people need to DM imogen to pay, I figure it's best to give them an easy way to do that (rather than being like, identify imogen in the group chat and then message her)

Open to critique

2022-01-24 21:39 UTC, cxloe commented
hm, should the example screenshots not have the slash prefix?

2022-01-27 19:48 UTC, transfaeries commented
> hm, should the example screenshots not have the slash prefix?

I don't know, should I take them off from every command definition too then? I want to be consistent

2022-01-31 20:38 UTC, technillogue commented
need to just change the screenshots that use /priority and this can be merged

2022-02-01 21:48 UTC, transfaeries commented
Ok, now I think this should be ready to merge. Please give final review.

2022-02-01 22:03 UTC, technillogue commented
yay!

2022-02-01 22:04 UTC, merged